<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseTemp extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('temp');
    $this->hasColumn('id_temp', 'integer', 4, array('type' => 'integer', 'unsigned' => '1', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
    $this->hasColumn('date', 'timestamp', 25, array('type' => 'timestamp', 'length' => '25'));
  }

}