<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseRole extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('role');
    $this->hasColumn('id_role', 'integer', 4, array('type' => 'integer', 'unsigned' => '1', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
    $this->hasColumn('role', 'string', 45, array('type' => 'string', 'notnull' => true, 'length' => '45'));
  }

  public function setUp()
  {
    $this->hasMany('User', array('local' => 'id_role',
                                 'foreign' => 'id_role'));
  }
}