<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseView extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('view');
    $this->hasColumn('id_view', 'integer', 4, array('type' => 'integer', 'unsigned' => '1', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
    $this->hasColumn('id_book', 'integer', 4, array('type' => 'integer', 'unsigned' => '1', 'notnull' => true, 'length' => '4'));
    $this->hasColumn('id_user', 'integer', 4, array('type' => 'integer', 'unsigned' => '1', 'notnull' => true, 'length' => '4'));
    $this->hasColumn('date_insert', 'timestamp', null, array('type' => 'timestamp', 'notnull' => true));
  }

  public function setUp()
  {
    $this->hasOne('User', array('local' => 'id_user',
                                'foreign' => 'id_user'));

    $this->hasOne('Book', array('local' => 'id_book',
                                'foreign' => 'id_book'));

    $timestampable0 = new Doctrine_Template_Timestampable(array('created' => array('name' => 'date_insert'), 'updated' => array('disabled' => true)));
    $this->actAs($timestampable0);
  }
}