<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseBook extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('book');
    $this->hasColumn('id_book', 'integer', 4, array('type' => 'integer', 'unsigned' => '1', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
    $this->hasColumn('id_author', 'integer', 4, array('type' => 'integer', 'unsigned' => '1', 'length' => '4'));
    $this->hasColumn('id_genre', 'integer', 4, array('type' => 'integer', 'unsigned' => '1', 'length' => '4'));
    $this->hasColumn('rating', 'integer', 1, array('type' => 'integer', 'unsigned' => '1', 'default' => '0', 'length' => '1'));
    $this->hasColumn('date_insert', 'timestamp', null, array('type' => 'timestamp', 'notnull' => true));
    $this->hasColumn('name', 'string', 45, array('type' => 'string', 'length' => '45'));
    $this->hasColumn('illustration', 'string', 45, array('type' => 'string', 'length' => '45'));
    $this->hasColumn('fact', 'string', 2147483647, array('type' => 'string', 'length' => '2147483647'));
    $this->hasColumn('year_create', 'string', 4, array('type' => 'string', 'length' => '4'));
  }

  public function setUp()
  {
    $this->hasOne('Genre', array('local' => 'id_genre',
                                 'foreign' => 'id_genre'));

    $this->hasOne('Author', array('local' => 'id_author',
                                  'foreign' => 'id_author'));

    $this->hasMany('Comment', array('local' => 'id_book',
                                    'foreign' => 'id_book'));

    $this->hasMany('View', array('local' => 'id_book',
                                 'foreign' => 'id_book'));

    $timestampable0 = new Doctrine_Template_Timestampable(array('created' => array('name' => 'date_insert'), 'updated' => array('disabled' => true)));
    $this->actAs($timestampable0);
  }
}