<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BookTable extends Doctrine_Table
{
    public function getBook()
    {
        $q = $this->createQuery('b');
        return $q->execute();
    }

    public function getTopBook()
    {
        $q = $this->createQuery('b')
            ->orderBy ('b.rating desc')
            ->limit(3);
        return $q->execute();
    }

    public function getNewBook()
    {
        $q = $this->createQuery('b')
            ->orderBy ('b.date_insert desc')
            ->limit(3);
        return $q->execute();
    }

    public function findBook($strSearch)
    {
        $q = $this->createQuery('b')
            ->leftJoin('b.Author a')
            ->where('lower(a.name) like \'%'. $strSearch .'%\'')
            ->orWhere('lower(b.name) like \'%'. $strSearch .'%\'');
        return $q->execute();
    }

    public function findByGenre($id_genre)
    {
        $q = $this->createQuery('b')
            ->where('b.id_genre = '. $id_genre);
        return $q->execute();
    }

    public function findByAuthor($id_author)
    {
        $q = $this->createQuery('b')
            ->where('b.id_author = '. $id_author);
        return $q->execute();
    }
}