<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BookTable extends Doctrine_Table
{
    public function getAllBooks()
    {
        $q = $this->createQuery('b');
        return $q->execute();
    }

    public function getTop100Books()
    {
        $q = $this->createQuery('b')
            ->orderBy ('b.rating desc')
            ->limit(100);
        return $q->execute();
    }

    public function getNew100Books()
    {
        $q = $this->createQuery('b')
            ->orderBy ('b.date_insert desc')
            ->limit(100);
        return $q->execute();
    }

    public function findBook($strSearch)
    {
        $q = $this->createQuery('b')
            ->leftJoin('b.Author a')
            ->where('lower(a.name) like \'%'. $strSearch .'%\'')
            ->orWhere('lower(b.name) like \'%'. $strSearch .'%\'');
        return $q->execute();
    }

    public function findByGenre($genreId)
    {
        $q = $this->createQuery('b')
            ->where('b.id_genre = '. $genreId);
        return $q->execute();
    }

    public function findByAuthor($authorId)
    {
        $q = $this->createQuery('b')
            ->where('b.id_author = '. $authorId);
        return $q->execute();
    }
}