<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CommentTable extends Doctrine_Table
{
  public function getComment($login)
  {
    $q = $this->createQuery('c')
      ->leftJoin('c.User u')
      ->where('c.id_user = u.id_user')
      ->andWhere('u.login = \'' . $login . '\'');
      return $q->execute();
    }

    public function getLastComment($login)
    {
      $q = $this->createQuery('c')
        ->leftJoin('c.User u')
        ->where('c.id_user = u.id_user')
        ->andWhere('u.login != \'' . $login . '\'')
        ->orderBy ('c.date_insert desc')
        ->limit(50);
      return $q->execute();
    }

    public function findBookComment($bookId)
    {
      $q = $this->createQuery('c')
        ->where('c.id_book = '. $bookId);
      return $q->execute();
    }

    public function getBookRating($bookId)
    {
      $q = $this->createQuery('c')
        ->select('round(avg(c.rating),0) as rating')
        ->where('c.id_book = '. $bookId);
      return $q->fetchOne();
    }
}