<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GenreTable extends Doctrine_Table
{
    public function getAllGenres()
    {
        $q = $this->createQuery('g');
        return $q->execute();
    }
}