<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RoleTable extends Doctrine_Table
{
    public function getRole($role)
    {
        $q = $this->createQuery('r')
            ->where('r.role = \'' . $role . '\'');
        return $q->fetchOne();
    }
}