default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [bootstrap.min.css, font-awesome.min.css, fontawesome-stars.css, reset.css, main.css, index.css]

  javascripts:    [jquery.js, bootstrap.js, main.js, jquery.uploadPreview.min.js, jquery.barrating.min.js, js_user_profile.js,jquery.windowScroll.js]

  has_layout:     true
  layout:         layout
