<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2018/07/11 17:56:07

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=new_library',
  'username' => 'root',
  'password' => 'Rfccbjgtz',
  'name' => 'doctrine',
)),);
