<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/07/11 17:56:07
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
