<?php
// auto-generated by sfViewConfigHandler
// date: 2018/07/11 17:56:07
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (!is_null($layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout')))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (is_null($this->getDecoratorTemplate()) && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('bootstrap.min.css', '', array ());
  $response->addStylesheet('font-awesome.min.css', '', array ());
  $response->addStylesheet('fontawesome-stars.css', '', array ());
  $response->addStylesheet('reset.css', '', array ());
  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('index.css', '', array ());
  $response->addJavascript('jquery.js', '', array ());
  $response->addJavascript('bootstrap.js', '', array ());
  $response->addJavascript('main.js', '', array ());
  $response->addJavascript('jquery.uploadPreview.min.js', '', array ());
  $response->addJavascript('jquery.barrating.min.js', '', array ());
  $response->addJavascript('js_user_profile.js', '', array ());
  $response->addJavascript('jquery.windowScroll.js', '', array ());


